### ISSUE TITLE
rose bush: handle cylc-suite.db located in log/, log.DATE_TIME.tar.gz

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1266] opened 2014-05-28 14:23 UTC
We should be able to handle cylc/cylc#966, and we should
think about support for viewing older log directories once this
has been implemented.

**Comment by matthewrmshin** [comment] 2015-02-09 15:07
Duplicate of #1030.

**Closed by matthewrmshin** 2015-02-09 15:07 UTC
Labels: duplicate
