### ISSUE TITLE
rose bush: sort by queue time and run time

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1770] opened 2015-12-04 12:50 UTC
It would be nice to be able to sort jobs by queue time and by run time in Rose Bush.

**Comment by matthewrmshin** [comment] 2015-12-04 12:54
Duplicate of #1018.

**Closed by matthewrmshin** 2015-12-04 12:54 UTC
Labels: duplicate

**Comment by arjclark** [comment] 2015-12-07 09:14
Erm, not a duplicate of #1018 as that doesn't sort jobs by queue or run time in rose bush.

**Comment by matthewrmshin** [comment] 2015-12-07 09:19
It is covered by the *etc* bit. The idea of #1018 is that once we have the `task_job_logs` table, we can do all of these queries that were very difficult to do before. Now that we have the `task_job_logs` table, we can easily cover sort by submit time, run time, exit time, queue duration, run duration, etc in a single change to Rose Bush.
